version: '3'
services:
  tests:
    image: pupp
    command: npm test
    depends_on:
      - setup
    volumes:
      - .:/app
  setup:
    build:
      context: .
      dockerfile: Dockerfile
    image: pupp